name: Build Advanced Production Planner

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas openpyxl numpy matplotlib seaborn tkcalendar pyinstaller

    - name: Build executable
      run: |
        pyinstaller --onefile --windowed --name "AdvancedProductionPlanner" production_planner_gui.py

    - name: Verify executable
      run: |
        if (Test-Path "dist\AdvancedProductionPlanner.exe") {
          echo "✅ Executable built successfully!"
          Get-ChildItem "dist\AdvancedProductionPlanner.exe"
        } else {
          echo "❌ Executable not found!"
          exit 1
        }

    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: Advanced-Production-Planner
        path: dist/AdvancedProductionPlanner.exe
